source = ~/.config/hypr/hyprland/common/programs.conf
source = ~/.config/hypr/hyprland/common/environment.conf

source = ~/.config/hypr/hyprland/common/autostart.conf
source = ~/.config/hypr/hyprland/common/input.conf
source = ~/.config/hypr/hyprland/common/keybind.conf
source = ~/.config/hypr/hyprland/common/looknfeel.conf
source = ~/.config/hypr/hyprland/common/workspace.conf


monitor=,preferred,auto,1.0
input {
    touchpad {
        natural_scroll = true
    }
}
