reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 10
    drafts: false
    base_branches:
      - "main"
    ignore_title_keywords:
      - "WIP"
      - "draft"
      - "bump"
      - "chore"
      - "[skip review]"
      - "Daily Nix Flake Update"