general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command (try hyprlock if not running)
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # wake up screen after suspend
}

# Reduce brightness after 2.5 minutes
listener {
    timeout = 150                                
    on-timeout = brightnessctl --save set 10%   # set monitor backlight to 10%
    on-resume = brightnessctl -restore          # restore monitor backlight
}

# Lock screen after 5 minutes
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           # lock screen
}

# Turn off screen after 5.5 minutes
listener {
    timeout = 330                                
    on-timeout = hyprctl dispatch dpms off && kb-light-manager off $vid $pid 
    on-resume = hyprctl dispatch dpms on && kb-light-manager on $vid $pid
}

