exec-once = uwsm-app -- waybar -c ./config/waybar/config.jsonc
exec-once = uwsm-app -- hyprpaper
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- foot --server

