exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = uwsm-app -- hyprpaper
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- waybar -c ~/.config/waybar/hyprland.jsonc
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- foot --server
exec-once = uwsm-app -- waydroid session start
exec-once = uwsm-app -- fcitx5 -r -d
