# See https://wiki.hyprland.org/Configuring/Keywords/
$terminal = kitty
$fileManager = yazi
$menu = rofi -show drun
$reload_waybar = pkill waybar; waybar -c ~/.config/waybar/hyprland.jsonc &
$snip = grimblast -f copysave area && notify-send "Screenshot Saved to File and Clipboard"
$snip_edit = GRIMBLAST_EDITOR="satty --filename" grimblast edit area && notify-send "Screenshot Saved to File and Clipboard"

