windowrule {
  name = float-wrapped-tui
  match:class = tui-float.*
  float = on
  center = on
  size = (monitor_w*0.5) (monitor_h*0.5)
}

windowrule {
  name = float-satty
  match:title = satty
  float = on
  center = on
  size = (monitor_w*0.5) (monitor_h*0.5)
}

windowrule {
  name = waydroid
  match:class = Waydroid
  float = on
  center = on
  size = (monitor_w*0.5) (monitor_h*0.5)
}

windowrule {
  name = waydroid-app
  match:class = waydroid.*
  float = on
  center = on
  size = (monitor_w*0.5) (monitor_h*0.5)
}
