"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](lavender)\
$os\
[](bg:sapphire fg:lavender)\
$directory\
[](bg:teal fg:sapphire)\
$git_branch\
$git_status\
$git_metrics\
[ ](fg:teal)\
$fill\
[](pink)\
$cmd_duration\
[](bg:pink fg:mauve)\
$time\
[ ](fg:mauve)\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:lavender fg:crust"

[os.symbols]
Ubuntu = "󰕈"
Linux  = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Arch   = "󰣇"
Debian = "󰣚"
NixOS  = " "

[directory]
style = "bg:sapphire fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "
"nix-config" = " "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:crust bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:crust bg:teal)]($style)'

[git_metrics]
disabled = false
style = "bg:teal"
format = '([$added $deleted ](fg:crust bg:teal))'

[time]
disabled = false
use_12hr = true
style = "bg:mauve"
format = '[[   $time ](fg:crust bg:mauve)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'

[cmd_duration]
format = '[[  in $duration ](fg:crust bg:pink)]($style)'
style = "bg:pink"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

