$vid = '32ac'
$pid = '0012'

source = ~/.config/hypr/hypridle/common/hypridle.conf

# Suspend should be a device specific setting
# Suspend pc after 10 minutes
listener {
    timeout = 600                                
    on-timeout = systemctl suspend-then-hibernate               # suspend pc
}
