source = ~/.config/hypr/common/autostart.conf
source = ~/.config/hypr/common/environment.conf
source = ~/.config/hypr/common/input.conf
source = ~/.config/hypr/common/keybind.conf
source = ~/.config/hypr/common/looknfeel.conf
source = ~/.config/hypr/common/programs.conf
source = ~/.config/hypr/common/workspace.conf

monitor=,preferred,auto,1.0
input {
    touchpad {
        natural_scroll = true
    }
}
