{
  imports = [
    ./boot.nix
    ./fonts.nix
    ./fwupd.nix
    ./hardware.nix
    ./kernel.nix
    ./keyring.nix
    ./networking.nix
    ./stylix.nix
    ./system.nix
    ./system_packages.nix
    ./user.nix
    ./fish-shell.nix
    ./flakpak.nix
    ./ssh.nix
    ./networkshare.nix
    ./usb_drive.nix
  ];
}
